---
title: "ICYMI: My talk on Introduction to Probabilistic Machine Learning"
author: Daniel Emaasit
date: '2017-08-14'
slug: introduction-to-probabilistic-machine-learning
categories:
  - R
  - Machine Learning
  - Bayesian
  - Data science
tags:
  - R
  - Machine Learning
  - Bayesian
  - Data Science
  - Meetup
summary: "Incase you missed it, here is a recording of my talk on Introduction to Probabilisitic Machine Learning at the Las Vegas R & Data Science Meetup groups. I introduced probabilistic machine learning and probabilistic programming with Stan. I discussed the basics of machine learning from a probabilistic/Bayesian perspective and contrasted it with traditional/algorithmic machine learning"  
---

Incase you missed it, here is a recording of my talk on Introduction to Probabilisitic Machine Learning at the Las Vegas R & Data Science Meetup groups.

I introduced probabilistic machine learning and probabilistic programming with Stan. I discussed the basics of machine learning from a probabilistic/Bayesian perspective and contrasted it with traditional/algorithmic machine learning. I also discussed how to build probabilistic models in computer code using a new exciting programming paradigm called Probabilistic Programming (PP). Particularly I used Stan (within R), a PP language, to build models ranging from simple generalized linear models to complex hierarchical models and nonparametric models for machine learning.

Slides and code can be found on Github [here](https://bit.ly/intro-pml-lv).

## Part I

<iframe width="560" height="315" src="https://www.youtube.com/embed/ICFtztrK9a4" frameborder="0" allowfullscreen></iframe>

## Part II

<iframe width="560" height="315" src="https://www.youtube.com/embed/YsGAce_3Ql4" frameborder="0" allowfullscreen></iframe>